[flake8]
max-line-length = 120
ignore = W605, W291
extend-ignore =
    # See https://github.com/PyCQA/pycodestyle/issues/373
    E203,
    # Missing docstring in public module
    D100,
    # Missing docstring in public class
    D101,
    # Missing docstring in public package
    D104,
    # Missing docstring in magic method
    D105,
    # Missing docstring in __init__
    D107,
    # First line should be in imperative mood
    D401,
    # module level import not at top of file
    E402,

exclude =
    .git
    __pycache__
    .ipynb_checkpoints
    dist
    build
    .tox
    venv/

[pydocstyle]
;add_ignore = D107, D203, D204, D213, D407, D406, D413